name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: windows-latest

    strategy:
      matrix:
        browser: [chrome, edge, firefox]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-xdist allure-pytest selenium webdriver-manager

      - name: Run tests
        run: |
          pytest -v tests/ --browser ${{ matrix.browser }} -n 3 --alluredir=reports/allure-results

      - name: Generate Allure Report
        run: |
          allure generate reports/allure-results -o reports/allure-report --clean
          allure open reports/allure-report
